version: '3'
services:
 mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  container_name: mysql
 
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: SpringIBM
    MYSQL_USER: root
    MYSQL_PASSWORD: Password@123